# Generated by Django 4.2.28 on 2026-03-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("MEMBER", "Member"),
                    ("SENIOR_MEMBER", "Senior Member"),
                    ("LEAD", "Team Lead"),
                    ("MANAGER", "Manager"),
                ],
                default="MEMBER",
                max_length=20,
            ),
        ),
    ]
