# Generated by Django 4.2.28 on 2026-03-13 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0002_alter_departmentmember_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentmember",
            name="can_close_tickets",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ticketdetail",
            name="TICKET_CLOSED_ON",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="mycart",
            unique_together={("user", "ticket")},
        ),
    ]
